# NumPy

In [1]:
import numpy as np # numpyのインポート

## NumPy配列の生成

In [2]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [3]:
type(x)

numpy.ndarray

## NumPyの算術計算

In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [5]:
x + y

array([3., 6., 9.])

In [6]:
x - y

array([-1., -2., -3.])

In [7]:
x * y   # element-wise product

array([ 2.,  8., 18.])

In [8]:
x / y

array([0.5, 0.5, 0.5])

* x, yの要素数が同じ (要素数3の1次元配列)
* 要素数が同じ場合、算術計算は各要素に対して行われる
* 要素ごとは、英語で「element-wise」と呼ばれる

In [9]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0 # スカラ値を組み合わせた計算は、

array([0.5, 1. , 1.5])

### 🤔NumPyを使わないで配列を計算するとどうなるか

In [10]:
a = [0, 1, 2]
b = [3, 4, 5]

In [11]:
a + b # 行列の結合

[0, 1, 2, 3, 4, 5]

In [12]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [13]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [14]:
a / b

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [15]:
a * 5

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

## NumPyのN次元配列

In [16]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [17]:
A.shape # 行列Aの形状。つまりこれは2次元配列であることを示す

(2, 2)

In [18]:
A.dtype # 要素のデータ型

dtype('int32')

In [19]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [20]:
A * 10

array([[10, 20],
       [30, 40]])

## ブロードキャスト

* 2次元配列とスカラ値の掛け算では、スカラ値が2次元配列に変換された後に計算される

In [21]:
A = np.array([[1, 2], [3, 4]]) # ((A1, A2), (A3, A4))
B = np.array([10, 20])         # (B1, B2)
A * B                          # = ((A1 * B1, A2 * B2), (A3 * B1, A4 * B2))

array([[10, 40],
       [30, 80]])

## 要素へのアクセス

In [22]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [23]:
X[0]

array([51, 55])

In [24]:
X[0][1]

55

In [25]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [26]:
X = X.flatten() # Xを1次元配列へ変換
print(X)

[51 55 14 19  0  4]


In [27]:
X[np.array([0, 2, 4])] # インデックスが0, 2, 4番目の要素を取得

array([51, 14,  0])

In [28]:
X > 15 # Xが15以上である要素の結果

array([ True,  True, False,  True, False, False])

In [29]:
X[X > 15] # Xが15以上の要素のみを抽出

array([51, 55, 19])